image: dendi04/gitlab-vue-kubectl-docker-doctl-plugin:v0.0.0.1

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375

stages:
  - test
  - build
  - deploy

before_script:
  - yarn install
  - yarn build  

test:
  stage: test 
  script:
    - yarn test --passWithNoTests
  only:
    - develop
    - master
    - merge_requests
    - tag

build-develop:
  stage: build
  script:
    - docker info
    - docker login -u $DOCKER_ID -p "$DOCKER_PASS"
    - docker build --pull --tag lokaventour/admin-vue:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA -f ./Dockerfile .
    - docker push lokaventour/admin-vue:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  only:
    - develop

build-qa:
  stage: build
  script:
    - docker info
    - docker login -u $DOCKER_ID -p "$DOCKER_PASS"
    - docker build --pull --tag lokaventour/admin-vue:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA -f ./Dockerfile .
    - docker push lokaventour/admin-vue:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  only:
    - master

deploy-to-dev:
  stage: deploy
  before_script:
    - doctl auth init --access-token $DO_TOKEN
    - doctl kubernetes cluster kubeconfig save lokaven
  script:
    - kubectl get nodes
    - kubectl set image deployment/admin-vue-deployment admin-vue=lokaventour/admin-vue:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  only:
    - develop

deploy-to-qa:
  stage: deploy
  before_script:
    - doctl auth init --access-token $DO_TOKEN
    - doctl kubernetes cluster kubeconfig save lokaven
  script:
    - kubectl get nodes
    - kubectl set image deployment/admin-qa admin-qa=lokaventour/admin-vue:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  only:
    - master