apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: admin-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - dev-staging.admin.lokaven.com
    secretName: echo-tls
  rules:
  - host: dev-staging.admin.lokaven.com
    http:
      paths:
      - backend:
          serviceName: admin-vue-service
          servicePort: 80